name: Run Daily at 09:05 UK time

on:
  schedule:
    - cron: '5 8 * * *'   # 09:05 UK time (summer)
    - cron: '5 9 * * *'   # 09:05 UK time (winter)
  workflow_dispatch:

jobs:
  your_job:
    runs-on: ubuntu-latest
    steps:
      - name: Example step
        run: echo "This workflow runs at 09:05 UK time"
