name: Tibia Discord Bot

on:
  schedule:
    - cron: '5 8 * * *'   # 09:05 UK time in summer (BST)
    - cron: '5 9 * * *'   # 09:05 UK time in winter (GMT)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Tibia Discord Bot
        run: python tibia_discord_bot.py
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
